dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
addons:
  apt:
    packages:
      - ant
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/download
before_script: composer install
script:
  - wget 'https://download.java.net/java/early_access/jdk8/b03/BCL/jre-8u202-ea-bin-b03-linux-x64-07_nov_2018.tar.gz'
  - tar xfz jre-8u202-ea-bin-b03-linux-x64-07_nov_2018.tar.gz
  - ./jre1.8.0_202/bin/java -version
  - java -version
  - CURR_DIR=`pwd`
  - export SOLR_JAVA_HOME="$CURR_DIR/jre1.8.0_202/"
  - echo "SOLR_JAVA_HOME is set to $SOLR_JAVA_HOME"
  - mysql --version
  - mkdir -p tests/workspace/cache tests/workspace/files tests/workspace/log tests/workspace/tmp
  - cp -p tests/config.ini.template tests/config.ini
  - sed -i -e "s!@db.admin.name@!root!" tests/config.ini
  - sed -i -e "s!@db.admin.password@!''!" tests/config.ini
  - sed -i -e "s!@db.name@!opusdb!" tests/config.ini
  - sed -i -e "s!@searchengine.default.host@!localhost!" tests/config.ini
  - sed -i -e "s!@searchengine.default.port@!8983!" tests/config.ini
  - sed -i -e "s!@searchengine.default.path@!/solr/opus4!" tests/config.ini
  - sed -i -e "s!@searchengine.index.host@!localhost!" tests/config.ini
  - sed -i -e "s!@searchengine.index.port@!8983!" tests/config.ini
  - sed -i -e "s!@searchengine.index.app@!/solr/opus4!" tests/config.ini
  - sed -i -e "s!@searchengine.extract.host@!localhost!" tests/config.ini
  - sed -i -e "s!@searchengine.extract.port@!8983!" tests/config.ini
  - sed -i -e "s!@searchengine.extract.app@!/solr/opus4!" tests/config.ini
  - cat tests/config.ini
  - php db/createdb.php
  - mysql opusdb -u root --password='' -e 'SELECT * FROM schema_version'
  - ant download-solr -DsolrVersion=5.5.5
  - cd solr-5.5.5
  - ./bin/solr start
  - ./bin/solr create -c opus4
  - cd server/solr/opus4/conf
  - rm -f managed-schema schema.xml solrconfig.xml
  - ln -s "$TRAVIS_BUILD_DIR/vendor/opus4-repo/search/schema-5.xml" schema.xml
  - ln -s "$TRAVIS_BUILD_DIR/vendor/opus4-repo/search/solrconfig-5.xml" solrconfig.xml
  - echo "$TRAVIS_BUILD_DIR"
  - cat schema.xml
  - cat solrconfig.xml
  - cd ../../../../
  - ./bin/solr restart
  - cd ..
  - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml
  - tail -200 solr-5.5.5/server/logs/solr.log
